-- Modulo Caja AMySA: registro de ingresos y egresos

create table if not exists public.amysa_cash_income (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_name text not null,
  unit_type text not null default 'unidad',
  quantity numeric(10,2) not null default 1,
  unit_price numeric(10,2) not null default 0,
  total numeric(12,2) not null default 0,
  was_sold boolean not null default true,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  constraint amysa_cash_income_unit_type_check check (unit_type in ('unidad', 'caja', 'paquete')),
  constraint amysa_cash_income_quantity_check check (quantity > 0),
  constraint amysa_cash_income_unit_price_check check (unit_price >= 0),
  constraint amysa_cash_income_total_check check (total >= 0)
);

create index if not exists idx_amysa_cash_income_created_at
  on public.amysa_cash_income (created_at desc);

create index if not exists idx_amysa_cash_income_product_name
  on public.amysa_cash_income (product_name);

create table if not exists public.amysa_cash_expense (
  id bigint generated by default as identity primary key,
  concept text not null,
  expense_type text not null default 'general',
  amount numeric(12,2) not null default 0,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  constraint amysa_cash_expense_type_check check (expense_type in ('compra', 'general')),
  constraint amysa_cash_expense_amount_check check (amount >= 0)
);

create index if not exists idx_amysa_cash_expense_created_at
  on public.amysa_cash_expense (created_at desc);

create index if not exists idx_amysa_cash_expense_type
  on public.amysa_cash_expense (expense_type);

alter table public.amysa_cash_income enable row level security;
alter table public.amysa_cash_expense enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'amysa_cash_income' and policyname = 'amysa_cash_income_service_all'
  ) then
    create policy amysa_cash_income_service_all
      on public.amysa_cash_income
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'amysa_cash_expense' and policyname = 'amysa_cash_expense_service_all'
  ) then
    create policy amysa_cash_expense_service_all
      on public.amysa_cash_expense
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end
$$;
