-- Modulo de marketing: cupones y mensajes de preencabezado

create table if not exists public.marketing_coupons (
  id bigint generated by default as identity primary key,
  code text not null,
  description text,
  discount_type text not null default 'percent',
  discount_value numeric(10,2) not null,
  min_subtotal numeric(10,2) not null default 0,
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_coupons_discount_type_check check (discount_type in ('percent', 'fixed')),
  constraint marketing_coupons_discount_value_check check (discount_value > 0),
  constraint marketing_coupons_min_subtotal_check check (min_subtotal >= 0)
);

create unique index if not exists idx_marketing_coupons_code_unique on public.marketing_coupons ((upper(code)));
create index if not exists idx_marketing_coupons_active on public.marketing_coupons (active);

create table if not exists public.marketing_preheader_messages (
  id bigint generated by default as identity primary key,
  message text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_marketing_preheader_messages_active_sort
  on public.marketing_preheader_messages (active, sort_order, id);

insert into public.marketing_preheader_messages (message, sort_order, active)
select 'CUPON DE APERTURA: AMYSA2026', 10, true
where not exists (select 1 from public.marketing_preheader_messages where message = 'CUPON DE APERTURA: AMYSA2026');

insert into public.marketing_preheader_messages (message, sort_order, active)
select 'PROMOCIONES DIA DE LA MADRE - COMPRA HOY', 20, true
where not exists (select 1 from public.marketing_preheader_messages where message = 'PROMOCIONES DIA DE LA MADRE - COMPRA HOY');

insert into public.marketing_preheader_messages (message, sort_order, active)
select 'ENVIO RAPIDO Y ATENCION PERSONALIZADA', 30, true
where not exists (select 1 from public.marketing_preheader_messages where message = 'ENVIO RAPIDO Y ATENCION PERSONALIZADA');

insert into public.marketing_preheader_messages (message, sort_order, active)
select 'NUEVOS INGRESOS TODAS LAS SEMANAS', 40, true
where not exists (select 1 from public.marketing_preheader_messages where message = 'NUEVOS INGRESOS TODAS LAS SEMANAS');

insert into public.marketing_preheader_messages (message, sort_order, active)
select 'APROVECHA OFERTAS EXCLUSIVAS ONLINE', 50, true
where not exists (select 1 from public.marketing_preheader_messages where message = 'APROVECHA OFERTAS EXCLUSIVAS ONLINE');

alter table public.marketing_coupons enable row level security;
alter table public.marketing_preheader_messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketing_coupons' and policyname = 'marketing_coupons_public_select_active'
  ) then
    create policy marketing_coupons_public_select_active
      on public.marketing_coupons
      for select
      to anon, authenticated
      using (
        active = true
        and (starts_at is null or starts_at <= now())
        and (ends_at is null or ends_at >= now())
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketing_coupons' and policyname = 'marketing_coupons_service_all'
  ) then
    create policy marketing_coupons_service_all
      on public.marketing_coupons
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketing_preheader_messages' and policyname = 'marketing_preheader_public_select_active'
  ) then
    create policy marketing_preheader_public_select_active
      on public.marketing_preheader_messages
      for select
      to anon, authenticated
      using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketing_preheader_messages' and policyname = 'marketing_preheader_service_all'
  ) then
    create policy marketing_preheader_service_all
      on public.marketing_preheader_messages
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end
$$;
